-- DATE FUNCTIONS
SELECT GETDATE() AS Today;

-- GET ONLY DATE OR ONLY TIME
SELECT CAST(GETDATE() AS DATE) AS day_today;

SELECT CAST(GETDATE() AS TIME) AS time_today;


-- EXAMPLE PRACTICE
--SELECT SUM(VENTAS) AS total_sales_today 
--FROM VENTAS 
--WHERE date_sales = CAST(GETDATE() AS DATE);


SELECT * FROM ventas;

SELECT DATETRUNC(MONTH, FECHA_VENTA) AS month_sales, FECHA_VENTA 
FROM ventas;

SELECT DATETRUNC(YEAR, FECHA_VENTA) AS year_sales, FECHA_VENTA
FROM ventas;

SELECT DATETRUNC(WEEK, FECHA_VENTA) AS week_sales, FECHA_VENTA
FROM ventas;


SELECT DATETRUNC(MONTH, FECHA_VENTA) AS month, SUM(VENTAS) AS SUM_VENTAS, AVG(VENTAS) AS AVG_VENTAS
FROM ventas
GROUP BY DATETRUNC(MONTH, FECHA_VENTA)
ORDER BY MONTH;

SELECT DATETRUNC(YEAR, FECHA_VENTA) AS YEAR, SUM(VENTAS) AS SUM_VENTAS, AVG(VENTAS) AS AVG_VENTAS
FROM ventas
GROUP BY DATETRUNC(YEAR, FECHA_VENTA)
ORDER BY YEAR;


SELECT * FROM votos;

SELECT CONCAT(ENTIDAD, ' ', DISTRITO_FEDERAL) AS ENTIDAD_COLONIA FROM votos;

SELECT SUBSTRING(ENTIDAD, 6, 10) AS WORD FROM votos;

SELECT LEN(ENTIDAD) AS LENGTH, ENTIDAD FROM votos;