-- DATE FUNCTIONS
SELECT GETDATE() AS Today;

-- GET ONLY DATE OR ONLY TIME
SELECT CAST(GETDATE() AS DATE) AS day_today;

SELECT CAST(GETDATE() AS TIME) AS time_today;

SELECT * FROM ventas;

-- EXAMPLE PRACTICE
--SELECT SUM(VENTAS) AS total_sales_today 
--FROM VENTAS 
--WHERE date_sales = CAST(GETDATE() AS DATE);