--- ORDER BY -----

SELECT *
FROM VOTOS;

--- SORT ASCENDENT ---
SELECT *
FROM VOTOS
ORDER BY ENTIDAD ASC;

--- SORT DESCENDENT ----
SELECT *
FROM VOTOS
ORDER BY ENTIDAD DESC;

--- SORT NULL ---
SELECT *
FROM VOTOS
ORDER BY DISTRITO_FEDERAL ASC;

--- SORT MULTIPLE ---
SELECT *
FROM VOTOS
ORDER BY Fecha_Publicación, ENTIDAD

--- LIMIT AND OFFSET ---
SELECT *
FROM VOTOS
ORDER BY ENTIDAD
OFFSET 0 ROW FETCH NEXT 10 ROWS ONLY;