CREATE DATABASE clasesql;

SELECT * FROM votos;
SELECT ID_ENTIDAD, Votos FROM votos;

SELECT ID_ENTIDAD, 
	ENTIDAD, 
	DISTRITO_FEDERAl AS 'DISTRITO ELECTORAL', 
	VOTOS,
	Fecha_Publicación AS FECHA
FROM VOTOS
WHERE votos < 200000;

SELECT *
FROM VOTOS
WHERE ENTIDAD = 'CHIHUAHUA';

SELECT ENTIDAD,
	DISTRITO_FEDERAL AS DISTRITO_ELECTORAL,
	Fecha_Publicación AS FECHA
FROM VOTOS
WHERE Fecha_Publicación <= '2024-06-04';

SELECT * 
FROM VOTOS
WHERE Fecha_Publicación > '2024-06-05'
AND ENTIDAD = 'MORELOS';

SELECT *
FROM VOTOS
WHERE Fecha_Publicación < '2024-06-05'
OR ENTIDAD = 'MORELOS';