--- ORDER BY -----

SELECT *
FROM VOTOS;

--- SORT ASCENDENT ---
SELECT *
FROM VOTOS
ORDER BY ENTIDAD ASC;

--- SORT DESCENDENT ----
SELECT *
FROM VOTOS
ORDER BY ENTIDAD DESC;

--- SORT NULL ---
SELECT *
FROM VOTOS
ORDER BY DISTRITO_FEDERAL ASC;

--- SORT MULTIPLE ---
SELECT *
FROM VOTOS
ORDER BY Fecha_Publicación, ENTIDAD

--- LIMIT AND OFFSET ---
SELECT *
FROM VOTOS
ORDER BY ENTIDAD
OFFSET 0 ROW FETCH NEXT 10 ROWS ONLY;

--- COUNT ---
SELECT COUNT(*)
FROM VOTOS;

SELECT COUNT(*) AS Boletas_Totales
FROM VOTOS;

SELECT COUNT(DISTRITO_FEDERAL)
FROM VOTOS;

--- WITH FILTER ---
SELECT COUNT(VOTOS) AS Boletas_Totales_Distritos_Sin_Nombre
FROM VOTOS
WHERE ENTIDAD = 'AGUASCALIENTES';

--- WITH FILTER NULL ---
SELECT COUNT(VOTOS) AS Boletas_Totales_Distritos_Sin_Nombre
FROM VOTOS
WHERE DISTRITO_FEDERAL IS NULL;

SELECT COUNT(VOTOS) AS Boletas_Totales_Distritos_Sin_Nombre
FROM VOTOS
WHERE DISTRITO_FEDERAL IS NULL
AND ENTIDAD IN ('AGUASCALIENTES', 'BAJA CALIFORNIA', 'CAMPECHE');

--- SUM ERROR---
--SELECT SUM(ENTIDAD)
--FROM VOTOS

SELECT SUM(VOTOS)AS TotalVotos
FROM VOTOS;

--- USE WHERE ---
SELECT SUM(VOTOS) AS TOTAL_VOTOS_AGUASCALIENTES
FROM VOTOS
WHERE ENTIDAD = 'AGUASCALIENTES';

SELECT SUM(VOTOS) AS TOTAL_VOTOS_SIN_NOMBRE
FROM VOTOS
WHERE DISTRITO_FEDERAL IS NULL;

SELECT SUM(VOTOS) AS Total_Votos_Sin_Nombre
FROM VOTOS
WHERE DISTRITO_FEDERAL IS NULL 
AND ENTIDAD IN ('AGUASCALIENTES','BAJA CALIFORNIA','CAMPECHE');

----- AVG -----
SELECT AVG(VOTOS) AS AvgTotal
FROM VOTOS

SELECT AVG(VOTOS) AS AvgTotalInsidePaz
FROM VOTOS
WHERE DISTRITO_FEDERAL LIKE '%PAZ%';

SELECT AVG(VOTOS) AS AvgTotalIsNull
FROM VOTOS
WHERE DISTRITO_FEDERAL IS NULL;

SELECT AVG(VOTOS) AS AvgTotalIsNullCustom
FROM VOTOS
WHERE DISTRITO_FEDERAL IS NULL
AND ENTIDAD IN ('AGUASCALIENTES','BAJA CALIFORNIA','CAMPECHE');

USE clasesql
CREATE TABLE tabla_texto(
	columna VARCHAR(255)
);

--- insert data txt data table tabla_texto

SELECT MIN(columna) AS word_min, MAX(columna) AS word_max
FROM tabla_texto


--- use table votos ----
--SELECT * FROM VOTOS ORDER BY VOTOS DESC;
SELECT MIN(DISTRITO_FEDERAL) AS MinValue, MAX(DISTRITO_FEDERAL) AS MaxValue
FROM VOTOS;

SELECT MIN(VOTOS) AS MinValue, MAX(VOTOS) AS MaxValue
FROM VOTOS;

SELECT MIN(VOTOS) AS MinValue, MAX(VOTOS) AS MaxValue
FROM VOTOS
WHERE Fecha_Publicación >= '2024-06-06';

SELECT MIN(VOTOS) AS MinValue, MAX(VOTOS) AS MaxValue
FROM VOTOS
WHERE DISTRITO_FEDERAL IS NULL;

SELECT MIN(VOTOS) AS MinValue, MAX(VOTOS) AS MaxValue
FROM VOTOS
WHERE DISTRITO_FEDERAL IS NULL
AND ENTIDAD IN ('AGUASCALIENTES','BAJA CALIFORNIA','CAMPECHE');

