----- ORDER SINTAXIS -----
--- 1:FROM, 2:WHERE, 3:GROUP BY, 4: SELECT, 5: ORDER BY

----CREATE DATABASE ------
CREATE DATABASE clasesql;

----- SELECT -------
SELECT * FROM votos;
SELECT ID_ENTIDAD, Votos FROM votos;

------ SELECT, WHERE ------
SELECT ID_ENTIDAD, 
	ENTIDAD, 
	DISTRITO_FEDERAl AS 'DISTRITO ELECTORAL', 
	VOTOS,
	Fecha_Publicación AS FECHA
FROM VOTOS
WHERE votos < 200000;

SELECT *
FROM VOTOS
WHERE ENTIDAD = 'CHIHUAHUA';

SELECT ENTIDAD,
	DISTRITO_FEDERAL AS DISTRITO_ELECTORAL,
	Fecha_Publicación AS FECHA
FROM VOTOS
WHERE Fecha_Publicación <= '2024-06-04';

----- SELECT, AND, OR -----
SELECT * 
FROM VOTOS
WHERE Fecha_Publicación > '2024-06-05'
AND ENTIDAD = 'MORELOS';

SELECT *
FROM VOTOS
WHERE Fecha_Publicación < '2024-06-05'
OR ENTIDAD = 'MORELOS';

------ IN ------
SELECT *
FROM VOTOS
WHERE ENTIDAD IN ('HIDALGO', 'PUEBLA', 'MORELOS');

---- select values distinct
SELECT DISTINCT Fecha_Publicación
FROM VOTOS;

---- < = > ----
SELECT *
FROM VOTOS
WHERE ENTIDAD IN ('NUEVO LEÓN', 'OAXACA','VERACRUZ')
AND Fecha_Publicación >= '2024-06-05' AND Fecha_Publicación <= '2024-06-06';

---- BETWEEN DATE -----
SELECT *
FROM VOTOS
WHERE ENTIDAD IN ('NUEVO LEÓN', 'OAXACA', 'VERACRUZ')
AND Fecha_Publicación BETWEEN '2024-06-05' AND '2024-06-06';


---- BETWEEN NUMBER
SELECT *
FROM VOTOS
WHERE ENTIDAD IN ('NUEVO LEÓN', 'OAXACA', 'VERACRUZ')
AND votos BETWEEN 180000 AND 200000;

---- BETWEEN TEXT -----
SELECT *
FROM VOTOS
WHERE ENTIDAD BETWEEN 'CHIHUAHUA' AND 'HIDALGO';

---- LIKE % ----
---- ANYWHERE ---
SELECT *
FROM VOTOS
WHERE DISTRITO_FEDERAL LIKE '%SANTIAGO%';

----- FIRST ----
SELECT *
FROM VOTOS
WHERE DISTRITO_FEDERAL LIKE 'SAN%';

---- LAST -----
SELECT *
FROM VOTOS
WHERE DISTRITO_FEDERAL LIKE '%PAZ';

---- IS NULL----
SELECT ENTIDAD,
	DISTRITO_FEDERAL AS COLONIA,
	VOTOS
FROM VOTOS
WHERE ENTIDAD IN ('AGUASCALIENTES','CAMPECHE','DURANGO','GUANAJUATO','MICHOACÁN')
AND DISTRITO_FEDERAL IS NULL;

---- IS NOT NULL ----
SELECT ENTIDAD,
	DISTRITO_FEDERAL AS COLONIA,
	VOTOS
FROM VOTOS
WHERE ENTIDAD IN ('AGUASCALIENTES','CAMPECHE','DURANGO','GUANAJUATO','MICHOACÁN')
AND DISTRITO_FEDERAL IS NOT NULL;

---- COALESCE ----
SELECT ENTIDAD,
	COALESCE(DISTRITO_FEDERAL, 'DISTRITO SIN NOMBRE') AS COLONIA,
	VOTOS
FROM VOTOS
WHERE ENTIDAD IN ('AGUASCALIENTES','CAMPECHE','DURANGO','GUANAJUATO','MICHOACÁN')
AND DISTRITO_FEDERAL IS NULL;