--USE clasesql
--SELECT * FROM poblacion

---- INNER JOIN ----

SELECT ENTIDAD, votos.DISTRITO_FEDERAL, votos, poblacion.población
FROM VOTOS INNER JOIN POBLACION
ON votos.DISTRITO_FEDERAL = POBLACION.DISTRITO_FEDERAL

SELECT ENTIDAD, V.DISTRITO_FEDERAL, VOTOS, P.población
FROM VOTOS AS V INNER JOIN POBLACION AS P
ON V.DISTRITO_FEDERAL = P.DISTRITO_FEDERAL
WHERE P.población > 1000000;

SELECT ENTIDAD, SUM(P.población) AS POBLACION_ESTATAL
FROM VOTOS AS V INNER JOIN poblacion AS P
ON V.DISTRITO_FEDERAL = P.DISTRITO_FEDERAL
WHERE ENTIDAD IN ('NAYARIT','HIDALGO','MORELOS')
GROUP BY ENTIDAD